### ISSUE TITLE
转onnx的步骤

### ISSUE THREAD

**Issue by lancelee98** [lovemefan/campplus#1]
大佬好牛，想问问你这边转onnx的步骤和思路，之前我也尝试过转但是转不成功

**Comment by lovemefan** [comment]
> 大佬好牛，想问问你这边转onnx的步骤和思路，之前我也尝试过转但是转不成功


你好呀，说话人识别的cam++，可直接trace导出
参考以下文件， eres2net 同理， 只需要替换onnx 模型文件即可

[CAM++导出笔记.pdf](https://github.com/lovemefan/campplus/files/13739593/CAM%2B%2B.pdf)

**Comment by lancelee98** [comment]
wow 看懂了 步骤非常详细 非常感谢大佬~
导出有if 或者for循环的复杂模型你这边有啥建议不

**Comment by lovemefan** [comment]
> wow 看懂了 步骤非常详细 非常感谢大佬~ 导出有if 或者for循环的复杂模型你这边有啥建议不

如果判断少，比较简单，参考torch.jit.script的用法，但是坑多。
如果逻辑复杂，可以拆模块。例如单独导出encoder，decoder，甚至是某几层，然后再自己把多个onnx模块拼起来。

**Comment by lancelee98** [comment]
谢谢~~~

**Comment by lovemefan** [comment]
> 谢谢~~~
不客气
